export interface Word {
  word: string;
  phonetic: string;
  translation: string;
  category: string;
}

export const IELTS_WORDS: Word[] = [
  { word: "abandon", phonetic: "[əˈbændən]", translation: "放弃", category: "Action" },
  { word: "abstract", phonetic: "[ˈæbstrækt]", translation: "抽象的", category: "Concept" },
  { word: "accumulate", phonetic: "[əˈkjuːmjəleɪt]", translation: "积累", category: "Action" },
  { word: "acknowledge", phonetic: "[əkˈnɒlɪdʒ]", translation: "承认", category: "Action" },
  { word: "acquire", phonetic: "[əˈkwaɪə(r)]", translation: "获得", category: "Action" },
  { word: "adequate", phonetic: "[ˈædɪkwət]", translation: "充足的", category: "Quality" },
  { word: "adjacent", phonetic: "[əˈdʒeɪsnt]", translation: "邻近的", category: "Position" },
  { word: "advocate", phonetic: "[ˈædvəkeɪt]", translation: "提倡", category: "Action" },
  { word: "ambiguous", phonetic: "[æmˈbɪɡjuəs]", translation: "模棱两可的", category: "Quality" },
  { word: "anticipate", phonetic: "[ænˈtɪsɪpeɪt]", translation: "预料", category: "Action" },
  { word: "apparent", phonetic: "[əˈpærənt]", translation: "明显的", category: "Quality" },
  { word: "appreciate", phonetic: "[əˈpriːʃieɪt]", translation: "欣赏", category: "Action" },
  { word: "appropriate", phonetic: "[əˈprəʊpriət]", translation: "适当的", category: "Quality" },
  { word: "arbitrary", phonetic: "[ˈɑːbɪtrəri]", translation: "任意的", category: "Quality" },
  { word: "assemble", phonetic: "[əˈsembl]", translation: "集合", category: "Action" },
  { word: "assess", phonetic: "[əˈses]", translation: "评估", category: "Action" },
  { word: "attribute", phonetic: "[əˈtrɪbjuːt]", translation: "属性", category: "Concept" },
  { word: "available", phonetic: "[əˈveɪləbl]", translation: "可用的", category: "Quality" },
  { word: "benefit", phonetic: "[ˈbenɪfɪt]", translation: "利益", category: "Concept" },
  { word: "bias", phonetic: "[ˈbaɪəs]", translation: "偏见", category: "Concept" },
  { word: "capable", phonetic: "[ˈkeɪpəbl]", translation: "有能力的", category: "Quality" },
  { word: "capacity", phonetic: "[kəˈpæsəti]", translation: "容量", category: "Concept" },
  { word: "category", phonetic: "[ˈkætəɡəri]", translation: "类别", category: "Concept" },
  { word: "cease", phonetic: "[siːs]", translation: "停止", category: "Action" },
  { word: "challenge", phonetic: "[ˈtʃælɪndʒ]", translation: "挑战", category: "Concept" },
  { word: "circumstance", phonetic: "[ˈsɜːkəmstəns]", translation: "情况", category: "Concept" },
  { word: "clarify", phonetic: "[ˈklærəfaɪ]", translation: "澄清", category: "Action" },
  { word: "coherent", phonetic: "[kəʊˈhɪərənt]", translation: "连贯的", category: "Quality" },
  { word: "collapse", phonetic: "[kəˈlæps]", translation: "崩溃", category: "Action" },
  { word: "commence", phonetic: "[kəˈmens]", translation: "开始", category: "Action" },
  { word: "commodity", phonetic: "[kəˈmɒdəti]", translation: "商品", category: "Object" },
  { word: "compatible", phonetic: "[kəmˈpætəbl]", translation: "兼容的", category: "Quality" },
  { word: "compensate", phonetic: "[ˈkɒmpenseɪt]", translation: "补偿", category: "Action" },
  { word: "complex", phonetic: "[ˈkɒmpleks]", translation: "复杂的", category: "Quality" },
  { word: "component", phonetic: "[kəmˈpəʊnənt]", translation: "组件", category: "Object" },
  { word: "comprehensive", phonetic: "[ˌkɒmprɪˈhensɪv]", translation: "全面的", category: "Quality" },
  { word: "concentrate", phonetic: "[ˈkɒnsntreɪt]", translation: "集中", category: "Action" },
  { word: "concept", phonetic: "[ˈkɒnsept]", translation: "概念", category: "Concept" },
  { word: "conclude", phonetic: "[kənˈkluːd]", translation: "结论", category: "Action" },
  { word: "conduct", phonetic: "[kənˈdʌkt]", translation: "传导", category: "Action" },
  { word: "confine", phonetic: "[kənˈfaɪn]", translation: "限制", category: "Action" },
  { word: "confirm", phonetic: "[kənˈfɜːm]", translation: "确认", category: "Action" },
  { word: "conflict", phonetic: "[ˈkɒnflɪkt]", translation: "冲突", category: "Concept" },
  { word: "conform", phonetic: "[kənˈfɔːm]", translation: "遵守", category: "Action" },
  { word: "consent", phonetic: "[kənˈsent]", translation: "同意", category: "Action" },
  { word: "considerable", phonetic: "[kənˈsɪdərəbl]", translation: "相当大的", category: "Quality" },
  { word: "constant", phonetic: "[ˈkɒnstənt]", translation: "恒定的", category: "Quality" },
  { word: "constitute", phonetic: "[ˈkɒnstɪtjuːt]", translation: "构成", category: "Action" },
  { word: "constrain", phonetic: "[kənˈstreɪn]", translation: "约束", category: "Action" },
  { word: "construct", phonetic: "[kənˈstrʌkt]", translation: "建造", category: "Action" },
  { word: "consult", phonetic: "[kənˈsʌlt]", translation: "咨询", category: "Action" },
  { word: "consume", phonetic: "[kənˈsjuːm]", translation: "消耗", category: "Action" },
  { word: "contemporary", phonetic: "[kənˈtemprəri]", translation: "当代的", category: "Quality" },
  { word: "context", phonetic: "[ˈkɒntekst]", translation: "上下文", category: "Concept" },
  { word: "contradict", phonetic: "[ˌkɒntrəˈdɪkt]", translation: "反驳", category: "Action" },
  { word: "contrast", phonetic: "[ˈkɒntrɑːst]", translation: "对比", category: "Concept" },
  { word: "contribute", phonetic: "[kənˈtrɪbjuːt] ", translation: "贡献", category: "Action" },
  { word: "convert", phonetic: "[kənˈvɜːt]", translation: "转换", category: "Action" },
  { word: "convince", phonetic: "[kənˈvɪns]", translation: "说服", category: "Action" },
  { word: "cooperate", phonetic: "[kəʊˈɒpəreɪt]", translation: "合作", category: "Action" },
  { word: "coordinate", phonetic: "[kəʊˈɔːdɪneɪt]", translation: "协调", category: "Action" },
  { word: "core", phonetic: "[kɔː(r)]", translation: "核心", category: "Concept" },
  { word: "corporate", phonetic: "[ˈkɔːpərət]", translation: "公司的", category: "Quality" },
  { word: "correspond", phonetic: "[ˌkɒrəˈspɒnd]", translation: "通信", category: "Action" },
  { word: "crucial", phonetic: "[ˈkruːʃl]", translation: "至关重要的", category: "Quality" },
  { word: "culture", phonetic: "[ˈkʌltʃə(r)]", translation: "文化", category: "Concept" },
  { word: "currency", phonetic: "[ˈkʌrənsi]", translation: "货币", category: "Object" },
  { word: "cycle", phonetic: "[ˈsaɪkl]", translation: "循环", category: "Concept" },
  { word: "debate", phonetic: "[dɪˈbeɪt]", translation: "辩论", category: "Action" },
  { word: "decade", phonetic: "[ˈdekeɪd]", translation: "十年", category: "Time" },
  { word: "decline", phonetic: "[dɪˈklaɪn]", translation: "下降", category: "Action" },
  { word: "deduce", phonetic: "[dɪˈdjuːs]", translation: "推断", category: "Action" },
  { word: "define", phonetic: "[dɪˈfaɪn]", translation: "定义", category: "Action" },
  { word: "definite", phonetic: "[ˈdefɪnət]", translation: "明确的", category: "Quality" },
  { word: "demonstrate", phonetic: "[ˈdemənstreɪt]", translation: "证明", category: "Action" },
  { word: "deny", phonetic: "[dɪˈnai]", translation: "否认", category: "Action" },
  { word: "derive", phonetic: "[dɪˈraɪv]", translation: "源于", category: "Action" },
  { word: "design", phonetic: "[dɪˈzaɪn]", translation: "设计", category: "Action" },
  { word: "despite", phonetic: "[dɪˈspaɪt]", translation: "尽管", category: "Concept" },
  { word: "detect", phonetic: "[dɪˈtekt]", translation: "检测", category: "Action" },
  { word: "deviate", phonetic: "[ˈdiːvieɪt]", translation: "偏离", category: "Action" },
  { word: "device", phonetic: "[dɪˈvaɪs]", translation: "设备", category: "Object" },
  { word: "devote", phonetic: "[dɪˈvəʊt]", translation: "奉献", category: "Action" },
  { word: "differentiate", phonetic: "[ˌdɪfəˈrenʃieɪt]", translation: "区分", category: "Action" },
  { word: "dimension", phonetic: "[daɪˈmenʃn]", translation: "维度", category: "Concept" },
  { word: "diminish", phonetic: "[dɪˈmɪnɪʃ]", translation: "减少", category: "Action" },
  { word: "discrete", phonetic: "[dɪˈskriːt]", translation: "离散的", category: "Quality" },
  { word: "discriminate", phonetic: "[dɪˈskrɪmɪneɪt]", translation: "歧视", category: "Action" },
  { word: "displace", phonetic: "[dɪsˈpleɪs]", translation: "置换", category: "Action" },
  { word: "display", phonetic: "[dɪˈspleɪ]", translation: "显示", category: "Action" },
  { word: "dispose", phonetic: "[dɪˈspəʊz]", translation: "处理", category: "Action" },
  { word: "distinct", phonetic: "[dɪˈstɪŋkt]", translation: "明显的", category: "Quality" },
  { word: "distort", phonetic: "[dɪˈstɔːt]", translation: "扭曲", category: "Action" },
  { word: "distribute", phonetic: "[dɪˈstrɪbjuːt]", translation: "分发", category: "Action" },
  { word: "diverse", phonetic: "[daɪˈvɜːs]", translation: "多样的", category: "Quality" },
  { word: "document", phonetic: "[ˈdɒkjumənt]", translation: "文档", category: "Object" },
  { word: "domain", phonetic: "[dəˈmeɪn]", translation: "领域", category: "Concept" },
  { word: "domestic", phonetic: "[dəˈmestɪk]", translation: "国内的", category: "Quality" },
  { word: "dominate", phonetic: "[ˈdɒmɪneɪt]", translation: "统治", category: "Action" },
  { word: "draft", phonetic: "[drɑːft]", translation: "草案", category: "Object" },
  { word: "drama", phonetic: "[ˈdrɑːmə]", translation: "戏剧", category: "Concept" },
  { word: "duration", phonetic: "[djuˈreɪʃn]", translation: "持续时间", category: "Time" },
  { word: "dynamic", phonetic: "[daɪˈnæmɪk]", translation: "动态的", category: "Quality" },
  { word: "economy", phonetic: "[ɪˈkɒnəmi]", translation: "经济", category: "Concept" },
  { word: "edit", phonetic: "[ˈedɪt]", translation: "编辑", category: "Action" },
  { word: "element", phonetic: "[ˈelɪmənt]", translation: "元素", category: "Concept" },
  { word: "eliminate", phonetic: "[ɪˈlɪmɪneɪt]", translation: "消除", category: "Action" },
  { word: "emerge", phonetic: "[iˈmɜːdʒ]", translation: "出现", category: "Action" },
  { word: "emphasis", phonetic: "[ˈemfəsɪs]", translation: "强调", category: "Concept" },
  { word: "empirical", phonetic: "[ɪmˈpɪrɪkl]", translation: "经验主义的", category: "Quality" },
  { word: "enable", phonetic: "[ɪˈneɪbl]", translation: "使能够", category: "Action" },
  { word: "encounter", phonetic: "[ɪnˈkaʊntə(r)]", translation: "遭遇", category: "Action" },
  { word: "energy", phonetic: "[ˈenədʒi]", translation: "能量", category: "Concept" },
  { word: "enforce", phonetic: "[ɪnˈfɔːs]", translation: "执行", category: "Action" },
  { word: "enhance", phonetic: "[ɪnˈhɑːns]", translation: "增强", category: "Action" },
  { word: "enormous", phonetic: "[ɪˈnɔːməs]", translation: "巨大的", category: "Quality" },
  { word: "ensure", phonetic: "[ɪnˈʃʊə(r)]", translation: "确保", category: "Action" },
  { word: "entity", phonetic: "[ˈentəti]", translation: "实体", category: "Concept" },
  { word: "environment", phonetic: "[ɪnˈvaɪrənmənt]", translation: "环境", category: "Concept" },
  { word: "equate", phonetic: "[ɪˈkweɪt]", translation: "等同", category: "Action" },
  { word: "equip", phonetic: "[ɪˈkwɪp]", translation: "装备", category: "Action" },
  { word: "equivalent", phonetic: "[ɪˈkwɪvələnt]", translation: "等价的", category: "Quality" },
  { word: "erode", phonetic: "[ɪˈrəʊd]", translation: "侵蚀", category: "Action" },
  { word: "error", phonetic: "[ˈerə(r)]", translation: "错误", category: "Concept" },
  { word: "establish", phonetic: "[ɪˈstæblɪʃ]", translation: "建立", category: "Action" },
  { word: "estate", phonetic: "[ɪˈsteɪt]", translation: "财产", category: "Concept" },
  { word: "estimate", phonetic: "[ˈestɪmət]", translation: "估计", category: "Action" },
  { word: "ethic", phonetic: "[ˈeθɪk]", translation: "伦理", category: "Concept" },
  { word: "ethnic", phonetic: "[ˈeθnɪk]", translation: "种族的", category: "Quality" },
  { word: "evaluate", phonetic: "[ɪˈvæljueɪt]", translation: "评估", category: "Action" },
  { word: "eventual", phonetic: "[ɪˈventʃuəl]", translation: "最终的", category: "Quality" },
  { word: "evident", phonetic: "[ˈevɪdənt]", translation: "明显的", category: "Quality" },
  { word: "evolve", phonetic: "[iˈvɒlv]", translation: "进化", category: "Action" },
  { word: "exceed", phonetic: "[ɪkˈsiːd]", translation: "超过", category: "Action" },
  { word: "exclude", phonetic: "[ɪkˈskluːd]", translation: "排除", category: "Action" },
  { word: "exhibit", phonetic: "[ɪɡˈzɪbɪt]", translation: "展览", category: "Action" },
  { word: "expand", phonetic: "[ɪkˈspænd]", translation: "扩张", category: "Action" },
  { word: "expert", phonetic: "[ˈekspɜːt]", translation: "专家", category: "Person" },
  { word: "explicit", phonetic: "[ɪkˈsplɪsɪt]", translation: "明确的", category: "Quality" },
  { word: "exploit", phonetic: "[ɪkˈsplɔɪt]", translation: "利用", category: "Action" },
  { word: "export", phonetic: "[ˈekspɔːt]", translation: "出口", category: "Action" },
  { word: "expose", phonetic: "[ɪkˈspəʊz]", translation: "暴露", category: "Action" },
  { word: "external", phonetic: "[ɪkˈstɜːnl]", translation: "外部的", category: "Quality" },
  { word: "extract", phonetic: "[ˈekstrækt]", translation: "提取", category: "Action" },
  { word: "facilitate", phonetic: "[fəˈsɪlɪteɪt]", translation: "促进", category: "Action" },
  { word: "factor", phonetic: "[ˈfæktə(r)]", translation: "因素", category: "Concept" },
  { word: "feature", phonetic: "[ˈfiːtʃə(r)]", translation: "特征", category: "Concept" },
  { word: "federal", phonetic: "[ˈfedərəl]", translation: "联邦的", category: "Quality" },
  { word: "fee", phonetic: "[fiː]", translation: "费用", category: "Object" },
  { word: "file", phonetic: "[faɪl]", translation: "文件", category: "Object" },
  { word: "final", phonetic: "[ˈfaɪnl]", translation: "最终的", category: "Quality" },
  { word: "finance", phonetic: "[ˈfaɪnæns]", translation: "财务", category: "Concept" },
  { word: "finite", phonetic: "[ˈfaɪnaɪt]", translation: "有限的", category: "Quality" },
  { word: "flexible", phonetic: "[ˈfleksəbl]", translation: "灵活的", category: "Quality" },
  { word: "fluctuate", phonetic: "[ˈflʌktʃueɪt]", translation: "波动", category: "Action" },
  { word: "focus", phonetic: "[ˈfəʊkəs]", translation: "焦点", category: "Action" },
  { word: "format", phonetic: "[ˈfɔːmæt]", translation: "格式", category: "Concept" },
  { word: "formula", phonetic: "[ˈfɔːmjələ]", translation: "公式", category: "Object" },
  { word: "forthcoming", phonetic: "[ˌfɔːθˈkʌmɪŋ]", translation: "即将到来的", category: "Quality" },
  { word: "found", phonetic: "[faʊnd]", translation: "建立", category: "Action" },
  { word: "foundation", phonetic: "[faʊnˈdeɪʃn]", translation: "基础", category: "Concept" },
  { word: "framework", phonetic: "[ˈfreɪmwɜːk]", translation: "框架", category: "Concept" },
  { word: "function", phonetic: "[ˈfʌŋkʃn]", translation: "功能", category: "Concept" },
  { word: "fund", phonetic: "[fʌnd]", translation: "基金", category: "Object" },
  { word: "fundamental", phonetic: "[ˌfʌndəˈmentl]", translation: "基本的", category: "Quality" },
  { word: "furthermore", phonetic: "[ˌfɜːðəˈmɔː(r)]", translation: "此外", category: "Concept" },
  { word: "gender", phonetic: "[ˈdʒendə(r)]", translation: "性别", category: "Concept" },
  { word: "generate", phonetic: "[ˈdʒenəreɪt]", translation: "生成", category: "Action" },
  { word: "generation", phonetic: "[ˌdʒenəˈreɪʃn]", translation: "代", category: "Time" },
  { word: "globe", phonetic: "[ɡləʊb]", translation: "地球", category: "Object" },
  { word: "goal", phonetic: "[ɡəʊl]", translation: "目标", category: "Concept" },
  { word: "grade", phonetic: "[ɡreɪd]", translation: "等级", category: "Concept" },
  { word: "grant", phonetic: "[ɡrɑːnt]", translation: "授予", category: "Action" },
  { word: "guarantee", phonetic: "[ˌɡærənˈtiː]", translation: "保证", category: "Action" },
  { word: "guideline", phonetic: "[ˈɡaɪdlaɪn]", translation: "指南", category: "Object" },
  { word: "hence", phonetic: "[hens]", translation: "因此", category: "Concept" },
  { word: "hierarchy", phonetic: "[ˈhaɪərɑːki]", translation: "等级制度", category: "Concept" },
  { word: "highlight", phonetic: "[ˈhaɪlaɪt]", translation: "突出", category: "Action" },
  { word: "hypothesis", phonetic: "[haɪˈpɒθəsɪs]", translation: "假设", category: "Concept" },
  { word: "identical", phonetic: "[aɪˈdentɪkl]", translation: "相同的", category: "Quality" },
  { word: "identify", phonetic: "[aɪˈdentɪfaɪ]", translation: "识别", category: "Action" },
  { word: "ideology", phonetic: "[ˌaɪdiˈɒlədʒi]", translation: "意识形态", category: "Concept" },
  { word: "ignore", phonetic: "[ɪɡˈnɔː(r)]", translation: "忽略", category: "Action" },
  { word: "illustrate", phonetic: "[ˈɪləstreɪt]", translation: "说明", category: "Action" },
  { word: "image", phonetic: "[ˈɪmɪdʒ]", translation: "图像", category: "Object" },
  { word: "immigrate", phonetic: "[ˈɪmɪɡreɪt]", translation: "移民", category: "Action" },
  { word: "impact", phonetic: "[ˈɪmpækt]", translation: "影响", category: "Concept" },
  { word: "implement", phonetic: "[ˈɪmplɪment]", translation: "实施", category: "Action" },
  { word: "implicate", phonetic: "[ˈɪmplɪkeɪt]", translation: "牵连", category: "Action" },
  { word: "implicit", phonetic: "[ɪmˈplɪsɪt]", translation: "暗含的", category: "Quality" },
  { word: "imply", phonetic: "[ɪmˈplaɪ]", translation: "暗示", category: "Action" },
  { word: "impose", phonetic: "[ɪmˈpəʊz]", translation: "强加", category: "Action" },
  { word: "incentive", phonetic: "[ɪnˈsentɪv]", translation: "激励", category: "Concept" },
  { word: "incidence", phonetic: "[ˈɪnsɪdəns]", translation: "发生率", category: "Concept" },
  { word: "incline", phonetic: "[ɪnˈklaɪn]", translation: "倾斜", category: "Action" },
  { word: "income", phonetic: "[ˈɪnkʌm]", translation: "收入", category: "Object" },
  { word: "incorporate", phonetic: "[ɪnˈkɔːpəreɪt]", translation: "合并", category: "Action" },
  { word: "index", phonetic: "[ˈɪndeks]", translation: "索引", category: "Object" },
  { word: "indicate", phonetic: "[ˈɪndɪkeɪt]", translation: "表明", category: "Action" },
  { word: "individual", phonetic: "[ˌɪndɪˈvɪdʒuəl]", translation: "个人", category: "Person" },
  { word: "induce", phonetic: "[ɪnˈdjuːs]", translation: "诱导", category: "Action" },
  { word: "inevitable", phonetic: "[ɪnˈevɪtəbl]", translation: "不可避免的", category: "Quality" },
  { word: "infer", phonetic: "[ɪnˈfɜː(r)]", translation: "推断", category: "Action" },
  { word: "infrastructure", phonetic: "[ˈɪnfrəstrʌktʃə(r)]", translation: "基础设施", category: "Object" },
  { word: "inherent", phonetic: "[ɪnˈhɪərənt]", translation: "固有的", category: "Quality" },
  { word: "inhibit", phonetic: "[ɪnˈhɪbɪt]", translation: "抑制", category: "Action" },
  { word: "initial", phonetic: "[ɪˈnɪʃl]", translation: "最初的", category: "Quality" },
  { word: "initiate", phonetic: "[ɪˈnɪʃieɪt]", translation: "开始", category: "Action" },
  { word: "injure", phonetic: "[ˈɪndʒə(r)]", translation: "伤害", category: "Action" },
  { word: "innovate", phonetic: "[ˈɪnəveɪt]", translation: "创新", category: "Action" },
  { word: "input", phonetic: "[ˈɪnpʊt]", translation: "输入", category: "Object" },
  { word: "insert", phonetic: "[ɪnˈsɜːt]", translation: "插入", category: "Action" },
  { word: "insight", phonetic: "[ˈɪnsaɪt]", translation: "洞察力", category: "Concept" },
  { word: "inspect", phonetic: "[ɪnˈspekt]", translation: "检查", category: "Action" },
  { word: "instance", phonetic: "[ˈɪnstəns]", translation: "实例", category: "Concept" },
  { word: "institute", phonetic: "[ˈɪnstɪtjuːt]", translation: "研究所", category: "Object" },
  { word: "instruct", phonetic: "[ɪnˈstrʌkt]", translation: "指导", category: "Action" },
  { word: "integral", phonetic: "[ˈɪntɪɡrəl]", translation: "积分", category: "Quality" },
  { word: "integrate", phonetic: "[ˈɪntɪɡreɪt]", translation: "整合", category: "Action" },
  { word: "integrity", phonetic: "[ɪnˈteɡrəti]", translation: "完整性", category: "Concept" },
  { word: "intelligent", phonetic: "[ɪnˈtelɪdʒənt]", translation: "智能的", category: "Quality" },
  { word: "intense", phonetic: "[ɪnˈtens]", translation: "强烈的", category: "Quality" },
  { word: "interact", phonetic: "[ˌɪntərˈækt]", translation: "互动", category: "Action" },
  { word: "intermediate", phonetic: "[ˌɪntəˈmiːdiət]", translation: "中间的", category: "Quality" },
  { word: "internal", phonetic: "[ɪnˈtɜːnl]", translation: "内部的", category: "Quality" },
  { word: "interpret", phonetic: "[ɪnˈtɜːprɪt]", translation: "解释", category: "Action" },
  { word: "interval", phonetic: "[ˈɪntəvl]", translation: "间隔", category: "Time" },
  { word: "intervene", phonetic: "[ˌɪntəˈviːn]", translation: "干预", category: "Action" },
  { word: "intrinsic", phonetic: "[ɪnˈtrɪnzɪk]", translation: "内在的", category: "Quality" },
  { word: "invest", phonetic: "[ɪnˈvest]", translation: "投资", category: "Action" },
  { word: "investigate", phonetic: "[ɪnˈvestɪɡeɪt]", translation: "调查", category: "Action" },
  { word: "invoke", phonetic: "[ɪnˈvəʊk]", translation: "调用", category: "Action" },
  { word: "involve", phonetic: "[ɪnˈvɒlv]", translation: "涉及", category: "Action" },
  { word: "isolate", phonetic: "[ˈaɪsəleɪt]", translation: "隔离", category: "Action" },
  { word: "issue", phonetic: "[ˈɪʃuː]", translation: "问题", category: "Concept" },
  { word: "item", phonetic: "[ˈaɪtəm]", translation: "项目", category: "Object" },
  { word: "job", phonetic: "[dʒɒb]", translation: "工作", category: "Object" },
  { word: "journal", phonetic: "[ˈdʒɜːnl]", translation: "期刊", category: "Object" },
  { word: "justify", phonetic: "[ˈdʒʌstɪfaɪ]", translation: "证明...有理", category: "Action" },
  { word: "label", phonetic: "[ˈlɪbl]", translation: "标签", category: "Object" },
  { word: "labor", phonetic: "[ˈleɪbə(r)]", translation: "劳动", category: "Concept" },
  { word: "layer", phonetic: "[ˈleɪə(r)]", translation: "层", category: "Object" },
  { word: "lecture", phonetic: "[ˈlektʃə(r)]", translation: "讲座", category: "Object" },
  { word: "legal", phonetic: "[ˈliːɡl]", translation: "法律的", category: "Quality" },
  { word: "legislate", phonetic: "[ˈledʒɪsleɪt]", translation: "立法", category: "Action" },
  { word: "levy", phonetic: "[ˈlevi]", translation: "征收", category: "Action" },
  { word: "liberal", phonetic: "[ˈlɪbərəl]", translation: "自由的", category: "Quality" },
  { word: "license", phonetic: "[ˈlaɪsns]", translation: "执照", category: "Object" },
  { word: "likewise", phonetic: "[ˈlaɪkwaɪz]", translation: "同样地", category: "Concept" },
  { word: "link", phonetic: "[lɪŋk]", translation: "链接", category: "Object" },
  { word: "locate", phonetic: "[ləʊˈkeɪt]", translation: "定位", category: "Action" },
  { word: "logic", phonetic: "[ˈlɒdʒɪk]", translation: "逻辑", category: "Concept" },
  { word: "maintain", phonetic: "[meɪnˈteɪn]", translation: "维持", category: "Action" },
  { word: "major", phonetic: "[ˈmeɪdʒə(r)]", translation: "主要的", category: "Quality" },
  { word: "manipulate", phonetic: "[məˈnɪpjuleɪt]", translation: "操纵", category: "Action" },
  { word: "manual", phonetic: "[ˈmænjuəl]", translation: "手册", category: "Object" },
  { word: "margin", phonetic: "[ˈmɑːdʒɪn]", translation: "边缘", category: "Object" },
  { word: "mature", phonetic: "[məˈtʃʊə(r)]", translation: "成熟的", category: "Quality" },
  { word: "maximize", phonetic: "[ˈmæksɪmaɪz]", translation: "最大化", category: "Action" },
  { word: "mechanism", phonetic: "[ˈmekənɪzəm]", translation: "机制", category: "Concept" },
  { word: "media", phonetic: "[ˈmiːdiə]", translation: "媒体", category: "Object" },
  { word: "mediate", phonetic: "[ˈmiːdieɪt]", translation: "调解", category: "Action" },
  { word: "medical", phonetic: "[ˈmedɪkl]", translation: "医学的", category: "Quality" },
  { word: "medium", phonetic: "[ˈmiːdiəm]", translation: "媒介", category: "Object" },
  { word: "mental", phonetic: "[ˈmentl]", translation: "心理的", category: "Quality" },
  { word: "method", phonetic: "[ˈmeθəd]", translation: "方法", category: "Concept" },
  { word: "migrate", phonetic: "[maɪˈɡreɪt]", translation: "迁移", category: "Action" },
  { word: "military", phonetic: "[ˈmɪlətri]", translation: "军事的", category: "Quality" },
  { word: "minimal", phonetic: "[ˈmɪnɪməl]", translation: "最小的", category: "Quality" },
  { word: "minimize", phonetic: "[ˈmɪnɪmaɪz]", translation: "最小化", category: "Action" },
  { word: "minimum", phonetic: "[ˈmɪnɪməm]", translation: "最小值", category: "Object" },
  { word: "ministry", phonetic: "[ˈmɪnɪstri]", translation: "部", category: "Object" },
  { word: "minor", phonetic: "[ˈmaɪnə(r)]", translation: "较小的", category: "Quality" },
  { word: "mode", phonetic: "[məʊd]", translation: "模式", category: "Concept" },
  { word: "modify", phonetic: "[ˈmɒdɪfaɪ]", translation: "修改", category: "Action" },
  { word: "monitor", phonetic: "[ˈmɒnɪtə(r)]", translation: "监控", category: "Action" },
  { word: "motive", phonetic: "[ˈməʊtɪv]", translation: "动机", category: "Concept" },
  { word: "mutual", phonetic: "[ˈmjuːtʃuəl]", translation: "相互的", category: "Quality" },
  { word: "negate", phonetic: "[nɪˈɡeɪt]", translation: "否定", category: "Action" },
  { word: "network", phonetic: "[ˈnetwɜːk]", translation: "网络", category: "Object" },
  { word: "neutral", phonetic: "[ˈnjuːtrəl]", translation: "中立的", category: "Quality" },
  { word: "nevertheless", phonetic: "[ˌnevəðəˈles]", translation: "尽管如此", category: "Concept" },
  { word: "node", phonetic: "[nəʊd]", translation: "节点", category: "Object" },
  { word: "normal", phonetic: "[ˈnɔːml]", translation: "正常的", category: "Quality" },
  { word: "notion", phonetic: "[ˈnəʊʃn]", translation: "概念", category: "Concept" },
  { word: "notwithstanding", phonetic: "[ˌnɒtwɪθˈstændɪŋ]", translation: "尽管", category: "Concept" },
  { word: "nuclear", phonetic: "[ˈnjuːkliə(r)]", translation: "核的", category: "Quality" },
  { word: "objective", phonetic: "[əbˈdʒektɪv]", translation: "客观的", category: "Quality" },
  { word: "obtain", phonetic: "[əbˈteɪn]", translation: "获得", category: "Action" },
  { word: "obvious", phonetic: "[ˈɒbviəs]", translation: "明显的", category: "Quality" },
  { word: "occupy", phonetic: "[ˈɒkjupaɪ]", translation: "占据", category: "Action" },
  { word: "occur", phonetic: "[əˈkɜː(r)]", translation: "发生", category: "Action" },
  { word: "odd", phonetic: "[ɒd]", translation: "奇特的", category: "Quality" },
  { word: "offset", phonetic: "[ˈɒfset]", translation: "抵消", category: "Action" },
  { word: "ongoing", phonetic: "[ˈɒnɡəʊɪŋ]", translation: "进行中的", category: "Quality" },
  { word: "option", phonetic: "[ˈɒpʃn]", translation: "选项", category: "Object" },
  { word: "orient", phonetic: "[ˈɔːrient]", translation: "导向", category: "Action" },
  { word: "outcome", phonetic: "[ˈaʊtkʌm]", translation: "结果", category: "Concept" },
  { word: "output", phonetic: "[ˈaʊtpʊt]", translation: "输出", category: "Object" },
  { word: "overall", phonetic: "[ˌəʊvərˈɔːl]", translation: "全面的", category: "Quality" },
  { word: "overlap", phonetic: "[ˌəʊvəˈlæp]", translation: "重叠", category: "Action" },
  { word: "overseas", phonetic: "[ˌəʊvəˈsiːz]", translation: "海外的", category: "Quality" },
  { word: "panel", phonetic: "[ˈpænl]", translation: "面板", category: "Object" },
  { word: "paradigm", phonetic: "[ˈpærədaɪm]", translation: "范式", category: "Concept" },
  { word: "paragraph", phonetic: "[ˈpærəɡrɑːf]", translation: "段落", category: "Object" },
  { word: "parallel", phonetic: "[ˈpærəlel]", translation: "平行的", category: "Quality" },
  { word: "parameter", phonetic: "[pəˈræmɪtə(r)]", translation: "参数", category: "Object" },
  { word: "participate", phonetic: "[pɑːˈtɪsɪpeɪt]", translation: "参与", category: "Action" },
  { word: "partner", phonetic: "[ˈpɑːtnə(r)]", translation: "伙伴", category: "Person" },
  { word: "passive", phonetic: "[ˈpæsɪv]", translation: "被动的", category: "Quality" },
  { word: "perceive", phonetic: "[pəˈsiːv]", translation: "感知", category: "Action" },
  { word: "percent", phonetic: "[pəˈsent]", translation: "百分比", category: "Object" },
  { word: "period", phonetic: "[ˈpɪəriəd]", translation: "时期", category: "Time" },
  { word: "persist", phonetic: "[pəˈsɪst]", translation: "坚持", category: "Action" },
  { word: "perspective", phonetic: "[pəˈspektɪv]", translation: "视角", category: "Concept" },
  { word: "phase", phonetic: "[feɪz]", translation: "阶段", category: "Time" },
  { word: "phenomenon", phonetic: "[fəˈnɒmɪnən]", translation: "现象", category: "Concept" },
  { word: "philosophy", phonetic: "[fəˈlɒsəfi]", translation: "哲学", category: "Concept" },
  { word: "physical", phonetic: "[ˈfɪzɪkl]", translation: "物理的", category: "Quality" },
  { word: "plus", phonetic: "[plʌs]", translation: "加", category: "Concept" },
  { word: "policy", phonetic: "[ˈpɒləsi]", translation: "政策", category: "Concept" },
  { word: "portion", phonetic: "[ˈpɔːʃn]", translation: "部分", category: "Object" },
  { word: "pose", phonetic: "[pəʊz]", translation: "姿势", category: "Action" },
  { word: "positive", phonetic: "[ˈpɒzətɪv]", translation: "积极的", category: "Quality" },
  { word: "potential", phonetic: "[pəˈtenʃl]", translation: "潜在的", category: "Quality" },
  { word: "practitioner", phonetic: "[prækˈtɪʃənə(r)]", translation: "从业者", category: "Person" },
  { word: "precede", phonetic: "[prɪˈsiːd]", translation: "在...之前", category: "Action" },
  { word: "precise", phonetic: "[prɪˈsaɪs]", translation: "精确的", category: "Quality" },
  { word: "predict", phonetic: "[prɪˈdɪkt]", translation: "预测", category: "Action" },
  { word: "predominant", phonetic: "[prɪˈdɒmɪnənt]", translation: "占主导地位的", category: "Quality" },
  { word: "preliminary", phonetic: "[prɪˈlɪmɪnəri]", translation: "初步的", category: "Quality" },
  { word: "presume", phonetic: "[prɪˈzjuːm]", translation: "假定", category: "Action" },
  { word: "previous", phonetic: "[ˈpriːviəs]", translation: "以前的", category: "Quality" },
  { word: "primary", phonetic: "[ˈpraɪməri]", translation: "主要的", category: "Quality" },
  { word: "prime", phonetic: "[praɪm]", translation: "主要的", category: "Quality" },
  { word: "principal", phonetic: "[ˈprɪnsəpl]", translation: "主要的", category: "Quality" },
  { word: "principle", phonetic: "[ˈprɪnsəpl]", translation: "原则", category: "Concept" },
  { word: "prior", phonetic: "[ˈpraɪə(r)]", translation: "优先的", category: "Quality" },
  { word: "priority", phonetic: "[praɪˈɒrəti]", translation: "优先权", category: "Concept" },
  { word: "proceed", phonetic: "[prəˈsiːd]", translation: "进行", category: "Action" },
  { word: "process", phonetic: "[ˈprəʊses]", translation: "过程", category: "Concept" },
  { word: "professional", phonetic: "[prəˈfeʃənl]", translation: "专业的", category: "Quality" },
  { word: "prohibit", phonetic: "[prəˈhɪbɪt]", translation: "禁止", category: "Action" },
  { word: "project", phonetic: "[ˈprɒdʒekt]", translation: "项目", category: "Object" },
  { word: "promote", phonetic: "[prəˈməʊt]", translation: "促进", category: "Action" },
  { word: "proportion", phonetic: "[prəˈpɔːʃn]", translation: "比例", category: "Object" },
  { word: "prospect", phonetic: "[ˈprɒspect]", translation: "前景", category: "Concept" },
  { word: "protocol", phonetic: "[ˈprəʊtəkɒl]", translation: "协议", category: "Object" },
  { word: "psychology", phonetic: "[saɪˈkɒlədʒi]", translation: "心理学", category: "Concept" },
  { word: "publication", phonetic: "[ˌpʌblɪˈkeɪʃn]", translation: "出版", category: "Object" },
  { word: "publish", phonetic: "[ˈpʌblɪʃ]", translation: "发布", category: "Action" },
  { word: "purchase", phonetic: "[ˈpɜːtʃəs]", translation: "购买", category: "Action" },
  { word: "pursue", phonetic: "[pəˈsjuː]", translation: "追求", category: "Action" },
  { word: "qualitative", phonetic: "[ˈkwɒlɪtətɪv]", translation: "定性的", category: "Quality" },
  { word: "quote", phonetic: "[kwəʊt]", translation: "引用", category: "Action" },
  { word: "radical", phonetic: "[ˈrædɪkl]", translation: "激进的", category: "Quality" },
  { word: "random", phonetic: "[ˈrændəm]", translation: "随机的", category: "Quality" },
  { word: "range", phonetic: "[reɪndʒ]", translation: "范围", category: "Object" },
  { word: "ratio", phonetic: "[ˈreɪʃiəʊ]", translation: "比率", category: "Object" },
  { word: "rational", phonetic: "[ˈræʃnəl]", translation: "理性的", category: "Quality" },
  { word: "react", phonetic: "[riˈækt]", translation: "反应", category: "Action" },
  { word: "recover", phonetic: "[rɪˈkʌvə(r)]", translation: "恢复", category: "Action" },
  { word: "refine", phonetic: "[rɪˈfaɪn]", translation: "提炼", category: "Action" },
  { word: "regime", phonetic: "[reɪˈʒiːm]", translation: "政权", category: "Concept" },
  { word: "region", phonetic: "[ˈriːdʒən]", translation: "区域", category: "Object" },
  { word: "register", phonetic: "[ˈredʒɪstə(r)]", translation: "注册", category: "Action" },
  { word: "regulate", phonetic: "[ˈreɡjuleɪt]", translation: "调节", category: "Action" },
  { word: "reinforce", phonetic: "[ˌriːɪnˈfɔːs]", translation: "加强", category: "Action" },
  { word: "reject", phonetic: "[rɪˈdʒekt]", translation: "拒绝", category: "Action" },
  { word: "relax", phonetic: "[rɪˈlæks]", translation: "放松", category: "Action" },
  { word: "release", phonetic: "[rɪˈliːs]", translation: "发布", category: "Action" },
  { word: "relevant", phonetic: "[ˈreləvənt]", translation: "相关的", category: "Quality" },
  { word: "reluctance", phonetic: "[rɪˈlʌktəns]", translation: "不情愿", category: "Concept" },
  { word: "rely", phonetic: "[rɪˈlaɪ]", translation: "依靠", category: "Action" },
  { word: "remove", phonetic: "[rɪˈmuːv]", translation: "移除", category: "Action" },
  { word: "require", phonetic: "[rɪˈkwaɪə(r)]", translation: "要求", category: "Action" },
  { word: "research", phonetic: "[rɪˈsɜːtʃ]", translation: "研究", category: "Action" },
  { word: "reside", phonetic: "[rɪˈzaɪd]", translation: "居住", category: "Action" },
  { word: "resolve", phonetic: "[rɪˈzɒlv]", translation: "解决", category: "Action" },
  { word: "resource", phonetic: "[rɪˈsɔːs]", translation: "资源", category: "Object" },
  { word: "respond", phonetic: "[rɪˈspɒnd]", translation: "回应", category: "Action" },
  { word: "restore", phonetic: "[rɪˈstɔː(r)]", translation: "恢复", category: "Action" },
  { word: "restrain", phonetic: "[rɪˈstreɪn]", translation: "抑制", category: "Action" },
  { word: "restrict", phonetic: "[rɪˈstrɪkt]", translation: "限制", category: "Action" },
  { word: "retain", phonetic: "[rɪˈteɪn]", translation: "保留", category: "Action" },
  { word: "reveal", phonetic: "[rɪˈviːl]", translation: "揭露", category: "Action" },
  { word: "revenue", phonetic: "[ˈrevənjuː]", translation: "收入", category: "Object" },
  { word: "reverse", phonetic: "[rɪˈvɜːs]", translation: "反转", category: "Action" },
  { word: "revise", phonetic: "[rɪˈvaɪz]", translation: "修订", category: "Action" },
  { word: "revolution", phonetic: "[ˌrevəˈluːʃn]", translation: "革命", category: "Concept" },
  { word: "rigid", phonetic: "[ˈrɪdʒɪd]", translation: "僵硬的", category: "Quality" },
  { word: "role", phonetic: "[rəʊl]", translation: "角色", category: "Concept" },
  { word: "route", phonetic: "[ruːt]", translation: "路线", category: "Object" },
  { word: "scenario", phonetic: "[səˈnɑːriəʊ]", translation: "场景", category: "Concept" },
  { word: "schedule", phonetic: "[ˈʃedjuːl]", translation: "时间表", category: "Object" },
  { word: "scheme", phonetic: "[skiːm]", translation: "计划", category: "Concept" },
  { word: "scope", phonetic: "[skəʊp]", translation: "范围", category: "Concept" },
  { word: "section", phonetic: "[ˈsekʃn]", translation: "部分", category: "Object" },
  { word: "sector", phonetic: "[ˈsektə(r)]", translation: "部门", category: "Object" },
  { word: "secure", phonetic: "[sɪˈkjʊə(r)]", translation: "安全的", category: "Quality" },
  { word: "seek", phonetic: "[siːk]", translation: "寻求", category: "Action" },
  { word: "select", phonetic: "[sɪˈlekt]", translation: "选择", category: "Action" },
  { word: "sequence", phonetic: "[ˈsiːkwəns]", translation: "序列", category: "Object" },
  { word: "series", phonetic: "[ˈsɪəriːz]", translation: "系列", category: "Object" },
  { word: "shift", phonetic: "[ʃɪft]", translation: "转移", category: "Action" },
  { word: "significant", phonetic: "[sɪɡˈnɪfɪkənt]", translation: "显著的", category: "Quality" },
  { word: "similar", phonetic: "[ˈsɪmələ(r)]", translation: "相似的", category: "Quality" },
  { word: "simulate", phonetic: "[ˈsɪmjuleɪt]", translation: "模拟", category: "Action" },
  { word: "site", phonetic: "[saɪt]", translation: "网站", category: "Object" },
  { word: "so-called", phonetic: "[ˌsəʊ ˈkɔːld]", translation: "所谓的", category: "Quality" },
  { word: "sole", phonetic: "[səʊl]", translation: "唯一的", category: "Quality" },
  { word: "somewhat", phonetic: "[ˈsʌmwɒt]", translation: "稍微", category: "Concept" },
  { word: "source", phonetic: "[sɔːs]", translation: "来源", category: "Object" },
  { word: "specific", phonetic: "[spəˈsɪfɪk]", translation: "特定的", category: "Quality" },
  { word: "specify", phonetic: "[ˈspesɪfaɪ]", translation: "指定", category: "Action" },
  { word: "sphere", phonetic: "[sfɪə(r)]", translation: "领域", category: "Object" },
  { word: "stable", phonetic: "[ˈsteɪbl]", translation: "稳定的", category: "Quality" },
  { word: "statistic", phonetic: "[stəˈtɪstɪk]", translation: "统计", category: "Object" },
  { word: "status", phonetic: "[ˈsteɪtəs]", translation: "状态", category: "Concept" },
  { word: "straightforward", phonetic: "[ˌstreɪtˈfɔːwəd]", translation: "简单的", category: "Quality" },
  { word: "strategy", phonetic: "[ˈstrætədʒi]", translation: "策略", category: "Concept" },
  { word: "stress", phonetic: "[stres]", translation: "压力", category: "Concept" },
  { word: "structure", phonetic: "[ˈstrʌktʃə(r)]", translation: "结构", category: "Object" },
  { word: "style", phonetic: "[staɪl]", translation: "风格", category: "Concept" },
  { word: "submit", phonetic: "[səbˈmɪt]", translation: "提交", category: "Action" },
  { word: "subordinate", phonetic: "[səˈbɔːdɪnət]", translation: "下属", category: "Person" },
  { word: "subsequent", phonetic: "[ˈsʌbsɪkwənt]", translation: "随后的", category: "Quality" },
  { word: "subsidy", phonetic: "[ˈsʌbsədi]", translation: "补贴", category: "Object" },
  { word: "substitute", phonetic: "[ˈsʌbstɪtjuːt]", translation: "替代", category: "Action" },
  { word: "successor", phonetic: "[səkˈsesə(r)]", translation: "继任者", category: "Person" },
  { word: "sufficient", phonetic: "[səˈfɪʃnt]", translation: "足够的", category: "Quality" },
  { word: "sum", phonetic: "[sʌm]", translation: "总和", category: "Object" },
  { word: "summary", phonetic: "[ˈsʌməri]", translation: "摘要", category: "Object" },
  { word: "supplement", phonetic: "[ˈsʌplɪmənt]", translation: "补充", category: "Action" },
  { word: "survey", phonetic: "[ˈsɜːveɪ]", translation: "调查", category: "Action" },
  { word: "survive", phonetic: "[səˈvaɪv]", translation: "生存", category: "Action" },
  { word: "suspend", phonetic: "[səˈspend]", translation: "暂停", category: "Action" },
  { word: "sustain", phonetic: "[səˈsteɪn]", translation: "维持", category: "Action" },
  { word: "symbol", phonetic: "[ˈsɪmbl]", translation: "符号", category: "Object" },
  { word: "tape", phonetic: "[teɪp]", translation: "磁带", category: "Object" },
  { word: "target", phonetic: "[ˈtɑːɡɪt]", translation: "目标", category: "Object" },
  { word: "task", phonetic: "[tɑːsk]", translation: "任务", category: "Object" },
  { word: "team", phonetic: "[tiːm]", translation: "团队", category: "Person" },
  { word: "technical", phonetic: "[ˈteknɪkl]", translation: "技术上的", category: "Quality" },
  { word: "technique", phonetic: "[tekˈniːk]", translation: "技术", category: "Concept" },
  { word: "technology", phonetic: "[tekˈnɒlədʒi]", translation: "技术", category: "Concept" },
  { word: "temporary", phonetic: "[ˈtemprəri]", translation: "暂时的", category: "Quality" },
  { word: "tense", phonetic: "[tens]", translation: "紧张的", category: "Quality" },
  { word: "terminate", phonetic: "[ˈtɜːmɪneɪt]", translation: "终止", category: "Action" },
  { word: "text", phonetic: "[tekst]", translation: "文本", category: "Object" },
  { word: "theme", phonetic: "[θiːm]", translation: "主题", category: "Concept" },
  { word: "theory", phonetic: "[ˈθɪəri]", translation: "理论", category: "Concept" },
  { word: "thereby", phonetic: "[ˌðeəˈbaɪ]", translation: "从而", category: "Concept" },
  { word: "thesis", phonetic: "[ˈθiːsɪs]", translation: "论文", category: "Object" },
  { word: "topic", phonetic: "[ˈtɒpɪk]", translation: "话题", category: "Concept" },
  { word: "trace", phonetic: "[treɪs]", translation: "追踪", category: "Action" },
  { word: "tradition", phonetic: "[trəˈdɪʃn]", translation: "传统", category: "Concept" },
  { word: "transfer", phonetic: "[trænsˈfɜː(r)]", translation: "转移", category: "Action" },
  { word: "transform", phonetic: "[trænsˈfɔːm]", translation: "转换", category: "Action" },
  { word: "transit", phonetic: "[ˈtrænzɪt]", translation: "运输", category: "Action" },
  { word: "transmit", phonetic: "[trænsˈmɪt]", translation: "传输", category: "Action" },
  { word: "transport", phonetic: "[ˈtrænspɔːt]", translation: "运输", category: "Action" },
  { word: "trend", phonetic: "[trend]", translation: "趋势", category: "Concept" },
  { word: "trigger", phonetic: "[ˈtrɪɡə(r)]", translation: "触发", category: "Action" },
  { word: "ultimate", phonetic: "[ˈʌltɪmət]", translation: "最终的", category: "Quality" },
  { word: "undergo", phonetic: "[ˌʌndəˈɡəʊ]", translation: "经历", category: "Action" },
  { word: "underlie", phonetic: "[ˌʌndəˈlaɪ]", translation: "构成...的基础", category: "Action" },
  { word: "undertake", phonetic: "[ˌʌndəˈteɪk]", translation: "承担", category: "Action" },
  { word: "uniform", phonetic: "[ˈjuːnɪfɔːm]", translation: "统一的", category: "Quality" },
  { word: "unify", phonetic: "[ˈjuːnɪfaɪ]", translation: "统一", category: "Action" },
  { word: "unique", phonetic: "[juˈniːk]", translation: "独特的", category: "Quality" },
  { word: "unit", phonetic: "[ˈjuːnɪt]", translation: "单位", category: "Object" },
  { word: "universe", phonetic: "[ˈjuːnɪvɜːs]", translation: "宇宙", category: "Object" },
  { word: "update", phonetic: "[ˌʌpˈdeɪt]", translation: "更新", category: "Action" },
  { word: "utilize", phonetic: "[ˈjuːtəlaɪz]", translation: "利用", category: "Action" },
  { word: "valid", phonetic: "[ˈvælɪd]", translation: "有效的", category: "Quality" },
  { word: "vary", phonetic: "[ˈveəri]", translation: "变化", category: "Action" },
  { word: "vehicle", phonetic: "[ˈviːəkl]", translation: "车辆", category: "Object" },
  { word: "version", phonetic: "[ˈvɜːʃn]", translation: "版本", category: "Object" },
  { word: "via", phonetic: "[ˈvaɪə]", translation: "经由", category: "Concept" },
  { word: "violate", phonetic: "[ˈvɪəleɪt]", translation: "违反", category: "Action" },
  { word: "virtual", phonetic: "[ˈvɜːtʃuəl]", translation: "虚拟的", category: "Quality" },
  { word: "visible", phonetic: "[ˈvɪzəbl]", translation: "可见的", category: "Quality" },
  { word: "vision", phonetic: "[ˈvɪʒn]", translation: "视觉", category: "Concept" },
  { word: "visual", phonetic: "[ˈvɪʒuəl]", translation: "视觉的", category: "Quality" },
  { word: "volume", phonetic: "[ˈvɒljuːm]", translation: "体积", category: "Object" },
  { word: "voluntary", phonetic: "[ˈvɒləntri]", translation: "自愿的", category: "Quality" },
  { word: "welfare", phonetic: "[ˈwelfeə(r)]", translation: "福利", category: "Concept" },
  { word: "whereas", phonetic: "[ˌweərˈæz]", translation: "而", category: "Concept" },
  { word: "whereby", phonetic: "[weəˈbaɪ]", translation: "凭借", category: "Concept" }
];
